package de.powerizzle.coloreater.game.pictures

import de.powerizzle.coloreater.game.Category
import de.powerizzle.coloreater.game.PixelArt
import de.powerizzle.coloreater.game.Track

/** Easy: simple pictures with few colors, in five categories that keep coming around. */
object EasyPictures {
    val FRUITS = Category(
        "Fruits", run = 4, listOf(
            PixelArt(
                "Cherries", listOf(
                    "..........EE....",
                    ".........EEE....",
                    "........B.......",
                    ".......B.B......",
                    "......B...B.....",
                    ".....B.....B....",
                    "....B.......B...",
                    "..RRRR....RRRR..",
                    ".RWRRRR..RWRRRR.",
                    ".RWRRRR..RWRRRR.",
                    ".RRRRRR..RRRRRR.",
                    ".RRRRRD..RRRRRD.",
                    "..RRRD....RRRD..",
                )
            ),
            PixelArt(
                "Lemon", listOf(
                    ".........EE.....",
                    "........EEE.....",
                    ".....KKKKKKK....",
                    "...KKYYYYYYYKK..",
                    "..KYYWWYYYYYYYK.",
                    ".KYYWYYYYYYYYYYK",
                    "KKYYYYYYYYYYYYYK",
                    ".KYYYYYYYYYYYYOK",
                    "..KYYYYYYYYYYOK.",
                    "...KKYYYYYYOKK..",
                    ".....KKKKKKK....",
                )
            ),
            PixelArt(
                "Orange", listOf(
                    ".......EE.......",
                    "......EEEE......",
                    ".....KKBBKK.....",
                    "...KKOOOOOOKK...",
                    "..KOOYOOOOOOOK..",
                    ".KOOYOOOOOOOOOK.",
                    ".KOYOOOOOOOOOOK.",
                    "KOOOOOOOOOOOOOQK",
                    "KOOOOOOOOOOOOOQK",
                    "KOOOOOOOOOOOOQQK",
                    ".KOOOOOOOOOOOQK.",
                    ".KOOOOOOOOOOQQK.",
                    "..KOOOOOOOOQQK..",
                    "...KKQOOOQQKK...",
                    ".....KKKKKK.....",
                )
            ),
            PixelArt(
                "Apple", listOf(
                    ".......BB.......",
                    "......BB.GG.....",
                    "......B.GGGG....",
                    "....RRBRRGG.....",
                    "..RRRRRRRRRR....",
                    ".RRWRRRRRRRRR...",
                    ".RWWRRRRRRRRRR..",
                    "RRWRRRRRRRRRRRR.",
                    "RRRRRRRRRRRRRRR.",
                    "RRRRRRRRRRRRRRD.",
                    "RRRRRRRRRRRRRRD.",
                    ".RRRRRRRRRRRRDD.",
                    ".RRRRRRRRRRRRD..",
                    "..RRRRRRRRRRDD..",
                    "...RRRDDRRRDD...",
                    "....DDD..DDD....",
                )
            ),
            PixelArt(
                "Pear", listOf(
                    ".......B........",
                    ".......B.EE.....",
                    ".......BEEE.....",
                    "......MMMM......",
                    ".....MMMMMM.....",
                    ".....MWMMMG.....",
                    "....MWMMMMMG....",
                    "....MMMMMMMG....",
                    "...MWMMMMMMMG...",
                    "..MMMMMMMMMMMG..",
                    "..MMMMMMMMMMMG..",
                    ".MMMMMMMMMMMMGG.",
                    ".MMMMMMMMMMMMGG.",
                    ".MMMMMMMMMMMGGG.",
                    "..MMMMMMMMMGGG..",
                    "...GGMMMMGGGG...",
                    ".....GGGGGG.....",
                )
            ),
            PixelArt(
                "Banana", listOf(
                    ".............BB.",
                    "............KYBK",
                    "...........KYYK.",
                    "..........KYYYK.",
                    "..........KYYOK.",
                    ".........KYYYOK.",
                    "........KYYYYOK.",
                    ".......KYYYYOK..",
                    ".....KKYYYYOOK..",
                    "...KKYYYYYYOK...",
                    ".KKYYYYYYYOOK...",
                    "KBYYYYYYOOOK....",
                    ".KKOOOOOOKK.....",
                    "...KKKKKK.......",
                )
            ),
            PixelArt(
                "Plum", listOf(
                    "........B.......",
                    ".......B.EE.....",
                    "......VBVEEE....",
                    "...VVVVVVVV.....",
                    "..VVPPVVVVVVV...",
                    ".VVPVVVVVVVVVV..",
                    ".VPVVVVVVVVVVVN.",
                    ".VVVVVVVVVVVVVN.",
                    ".VVVVVVVVVVVVNN.",
                    "..VVVVVVVVVVVN..",
                    "..NVVVVVVVVVNN..",
                    "...NNVVVVVNNN...",
                    ".....NNNNNN.....",
                )
            ),
            PixelArt(
                "Grapes", listOf(
                    ".......B........",
                    ".......BEEE.....",
                    "......BEEEEE....",
                    "..VVVVBVVVEE....",
                    ".VPVVVVVPVV.....",
                    ".VVVNVPVVVNV....",
                    "..VVNVVVVNV.....",
                    "..VPVVVPVVVV....",
                    "..VVVNVVVNVV....",
                    "...VVVVPVVV.....",
                    "...VPVVVVNV.....",
                    "....VVNVVV......",
                    ".....VPVV.......",
                    "......VN........",
                )
            ),
        )
    )

    val ANIMALS = Category(
        "Animals", run = 2, listOf(
            PixelArt(
                "Fish", listOf(
                    ".......KKKK.....",
                    ".....KKOOOOKK...",
                    "K...KOOOWWOOOK..",
                    "KK.KOOOWKWOOOOK.",
                    "KOKOOOOOWWOOOOOK",
                    "KOOOOYYOOOOOOOOK",
                    "KOKOOOYYOOOOOOK.",
                    "KK.KOOOOOOOOOK..",
                    "K...KOOOOOOOK...",
                    ".....KKOOOKK....",
                    ".......KKK......",
                )
            ),
            PixelArt(
                "Snail", listOf(
                    ".K..K...........",
                    ".K..K...KKKKK...",
                    ".KKKK.KKOOOOOKK.",
                    "KTTTTKKOOKKKOOOK",
                    "KTWKTKOOKOOOKOOK",
                    "KTTTTKOOKOKOKOOK",
                    ".KTTTKOOKOOKKOOK",
                    ".KTTTKOOOKKOOOOK",
                    ".KTTTTKOOOOOOOK.",
                    ".KTTTTTKKKKKKKK.",
                    "..KTTTTTTTTTTTTK",
                    "...KKKKKKKKKKKK.",
                )
            ),
            PixelArt(
                "Duck", listOf(
                    "....KKKK........",
                    "...KYYYYK.......",
                    "..KYYKYYYK......",
                    "..KYYYYYYK......",
                    "KKKOYYYYYK......",
                    "KOOOKYYYYK...K..",
                    ".KKKYYYYYYK.KYK.",
                    "...KYYYYYYYKYYK.",
                    "..KYYYYYYYYYYYK.",
                    "..KYYYYOOYYYYYK.",
                    "..KYYYYYOOYYYYK.",
                    "..KYYYYYYYYYYK..",
                    "...KYYYYYYYYYK..",
                    "....KKKKKKKKK...",
                    "LALLLLALLLLLALLL",
                    "LLLLLLLLLLLLLLLL",
                )
            ),
            PixelArt(
                "Cat", listOf(
                    ".KK..........KK.",
                    ".KPK........KPK.",
                    ".KPCK......KCPK.",
                    ".KCCCKKKKKKCCCK.",
                    "KCCCCCCCCCCCCCCK",
                    "KCCKKCCCCCCKKCCK",
                    "KCCKMKCCCCKMKCCK",
                    "KCCKKCCCCCCKKCCK",
                    "KCCCCCWWWWCCCCCK",
                    "KCCCCWWPPWWCCCCK",
                    ".KCCCWWKKWWCCCK.",
                    "..KCCCWWWWCCCK..",
                    "...KKCCCCCCKK...",
                    ".....KKKKKK.....",
                )
            ),
            PixelArt(
                "Bee", listOf(
                    "......K...K.....",
                    ".......K.K......",
                    "..AAA..KK..AAA..",
                    ".AWWAA.KK.AAWWA.",
                    ".AWWWAKKKKAWWWA.",
                    "..AAAKYYYYKAAA..",
                    "....KYYYYYYK....",
                    "...KKKKKKKKKK...",
                    "...KYYYYYYYYK...",
                    "...KKKKKKKKKK...",
                    "...KYYYYYYYYK...",
                    "....KKKKKKKK....",
                    ".....KYYYYK.....",
                    "......KKKK......",
                    ".......K........",
                )
            ),
            PixelArt(
                "Mouse", listOf(
                    "..KKK......KKK..",
                    ".KCCCK....KCCCK.",
                    "KCPPCCK..KCCPPCK",
                    "KCPPCCKKKKCCPPCK",
                    "KCCCCCCCCCCCCCCK",
                    ".KKCCCCCCCCCCKK.",
                    "...KCKKCCKKCK...",
                    "...KCKWCCKWCK...",
                    "...KCCCCCCCCK...",
                    "..KCCCCPPCCCCK..",
                    ".K.KCCCPPCCCK.K.",
                    "....KCCCCCCK....",
                    ".....KKKKKK.....",
                )
            ),
        )
    )

    val FLOWERS = Category(
        "Flowers", run = 3, listOf(
            PixelArt(
                "Tulip", listOf(
                    "....R...R...R...",
                    "...RRR.RRR.RRR..",
                    "...RRRRRRRRRRR..",
                    "...RPRRRRRRRRR..",
                    "...RPRRRRRRRRD..",
                    "...RRRRRRRRRRD..",
                    "....RRRRRRRRD...",
                    ".....RRRRRRD....",
                    ".......GG.......",
                    ".......GG.......",
                    ".GG....GG....GG.",
                    ".GGG...GG...GGG.",
                    "..GGG..GG..GGG..",
                    "...GGG.GG.GGG...",
                    "....GGGGGGGG....",
                    ".......GG.......",
                )
            ),
            PixelArt(
                "Flower", listOf(
                    ".....YYYYYY.....",
                    "...YYYYYYYYYY...",
                    "..YYYYOOOOYYYY..",
                    ".YYYYOOOOOOYYYY.",
                    ".YYYOOOBBOOOYYY.",
                    ".YYYOOBBBBOOYYY.",
                    ".YYYOOBBBBOOYYY.",
                    ".YYYOOOBBOOOYYY.",
                    ".YYYYOOOOOOYYYY.",
                    "..YYYYOOOOYYYY..",
                    "...YYYYYYYYYY...",
                    ".....YYGGYY.....",
                    "..GG...GG...GG..",
                    "..GGGG.GG.GGGG..",
                    "...GGGGGGGGGG...",
                    ".......GG.......",
                )
            ),
            PixelArt(
                "Daisy", listOf(
                    "......CCC.......",
                    ".....CWWWC......",
                    "..CC.CWWWC.CC...",
                    ".CWWCCWWWCCWWC..",
                    ".CWWWCWWWCWWWC..",
                    "..CWWWYYYWWWC...",
                    "CCCCWYYOYYWCCCC.",
                    "CWWWWYOYOYWWWWC.",
                    "CCCCWYYOYYWCCCC.",
                    "..CWWWYYYWWWC...",
                    ".CWWWCWWWCWWWC..",
                    ".CWWCCWWWCCWWC..",
                    "..CC.CWWWC.CC...",
                    ".....CWWWC......",
                    "......CCC.......",
                    "......E.........",
                    "......E.EE......",
                    "....EE.E........",
                    "......E.........",
                )
            ),
            PixelArt(
                "Sunflower", listOf(
                    ".....Y..Y..Y....",
                    "...Y.YYYYYYY.Y..",
                    "....YYOOOOOYY...",
                    "..YYYOBBBBBOYYY.",
                    "...YOBBKBBBBOY..",
                    ".YYYOBBBBKBBOYYY",
                    "...YOBKBBBBBOY..",
                    "..YYYOBBBBBOYYY.",
                    "....YYOOOOOYY...",
                    "...Y.YYYYYYY.Y..",
                    ".....Y..Y..Y....",
                    "........G.......",
                    ".....EE.G.......",
                    "......EEG..EE...",
                    "........GEEE....",
                    "........G.......",
                )
            ),
            PixelArt(
                "Rose", listOf(
                    "......RRRR......",
                    "....RRDRRDRR....",
                    "...RDRRDDRRDR...",
                    "..RRDRDRRDRDRR..",
                    "..RDRDRRRRDRDR..",
                    "..RRDRRDDRRDRR..",
                    "...RRDDRRDDRR...",
                    "....RRRRRRRR....",
                    ".....DRRRRD.....",
                    ".......EE.......",
                    "..EEE..E........",
                    ".EEMEE.E..EEE...",
                    "..EEEEEE.EMMEE..",
                    ".......EEEEE....",
                    ".......E........",
                    ".......E........",
                )
            ),
            PixelArt(
                "Cactus", listOf(
                    ".......PP.......",
                    "......PYYP......",
                    ".......PP.......",
                    "......EGGE......",
                    "......GGGG......",
                    "..EE..GMGG......",
                    "..GG..GMGG..EE..",
                    "..GG..GGGG..GG..",
                    "..GGGGGMGG..GG..",
                    "...GGGGGGGGGGG..",
                    "......GMGGGGG...",
                    "......GGGG......",
                    "......GGGG......",
                    "...OOOOOOOOOO...",
                    "....QOOOOOOQ....",
                    "....QOOOOOOQ....",
                    ".....QQQQQQ.....",
                )
            ),
        )
    )

    val SHAPES = Category(
        "Shapes", run = 3, listOf(
            PixelArt(
                "Heart", listOf(
                    "..KKKK....KKKK..",
                    ".KRRRRK..KRRRRK.",
                    "KRRWWRRKKRRRRRRK",
                    "KRRWRRRRRRRRRRRK",
                    "KRRRRRRRRRRRRRRK",
                    "KRRRRRRRRRRRRRRK",
                    "KRRRRRRRRRRRRRDK",
                    ".KRRRRRRRRRRRDK.",
                    "..KRRRRRRRRRDK..",
                    "...KRRRRRRRDK...",
                    "....KRRRRRDK....",
                    ".....KRRRDK.....",
                    "......KRDK......",
                    ".......KK.......",
                )
            ),
            PixelArt(
                "Star", listOf(
                    ".......KK.......",
                    "......KYYK......",
                    "......KYYK......",
                    ".....KYYYYK.....",
                    "KKKKKKYYYYKKKKKK",
                    "KYYYYYYYYYYYYYYK",
                    ".KYYYYYWYYYYYYK.",
                    "..KYYYYYYYYYYK..",
                    "...KYYYYYYYYK...",
                    "...KYYYYYYYYK...",
                    "..KYYYYYYYYYYK..",
                    "..KYYYYKKYYYYK..",
                    ".KYYYKK..KKYYYK.",
                    ".KYKK......KKYK.",
                    ".KK..........KK.",
                )
            ),
            PixelArt(
                "Smiley", listOf(
                    ".....KKKKKK.....",
                    "...KKYYYYYYKK...",
                    "..KYYYYYYYYYYK..",
                    ".KYYYYYYYYYYYYK.",
                    ".KYYYKYYYYKYYYK.",
                    "KYYYYKYYYYKYYYYK",
                    "KYYYYKYYYYKYYYYK",
                    "KYYYYYYYYYYYYYYK",
                    "KYPPYYYYYYYYPPYK",
                    "KYYKYYYYYYYYKYYK",
                    ".KYYKYYYYYYKYYK.",
                    ".KYYYKKKKKKYYYK.",
                    "..KYYYYYYYYYYK..",
                    "...KKYYYYYYKK...",
                    ".....KKKKKK.....",
                )
            ),
            PixelArt(
                "Dice", listOf(
                    ".KKKKKKKKKKKKKK.",
                    "KWWWWWWWWWWWWWWK",
                    "KWKKWWWWWWWWKKWK",
                    "KWKKWWWWWWWWKKWK",
                    "KWWWWWWWWWWWWWWK",
                    "KWWWWWWWWWWWWWWK",
                    "KWWWWWWWWWWWWWWK",
                    "KWWWWWWKKWWWWWWK",
                    "KWWWWWWKKWWWWWWK",
                    "KWWWWWWWWWWWWWWK",
                    "KWWWWWWWWWWWWWWK",
                    "KWWWWWWWWWWWWWWK",
                    "KWKKWWWWWWWWKKWK",
                    "KWKKWWWWWWWWKKWK",
                    "KWWWWWWWWWWWWWWK",
                    ".KKKKKKKKKKKKKK.",
                )
            ),
            PixelArt(
                "Target", listOf(
                    ".....KKKKKK.....",
                    "...KKRRRRRRKK...",
                    "..KRRWWWWWWRRK..",
                    ".KRWWRRRRRRWWRK.",
                    ".KRWRRWWWWRRWRK.",
                    "KRWRWWRRRRWWRWRK",
                    "KRWRWRRLLRRWRWRK",
                    "KRWRWRLLLLRWRWRK",
                    "KRWRWRLLLLRWRWRK",
                    "KRWRWRRLLRRWRWRK",
                    "KRWRWWRRRRWWRWRK",
                    ".KRWRRWWWWRRWRK.",
                    ".KRWWRRRRRRWWRK.",
                    "..KRRWWWWWWRRK..",
                    "...KKRRRRRRKK...",
                    ".....KKKKKK.....",
                )
            ),
            PixelArt(
                "Chess", listOf(
                    "BBBBBBBBBBBBBBBB",
                    "BWWKKWWKKWWKKWWB",
                    "BWWKKWWKKWWKKWWB",
                    "BKKWWKKWWKKWWKKB",
                    "BKKWWKKWWKKWWKKB",
                    "BWWKKWWKKWWKKWWB",
                    "BWWKKWWKKWWKKWWB",
                    "BKKWWKKWWKKWWKKB",
                    "BKKWWKKWWKKWWKKB",
                    "BWWKKWWKKWWKKWWB",
                    "BWWKKWWKKWWKKWWB",
                    "BKKWWKKWWKKWWKKB",
                    "BKKWWKKWWKKWWKKB",
                    "BWWKKWWKKWWKKWWB",
                    "BWWKKWWKKWWKKWWB",
                    "BBBBBBBBBBBBBBBB",
                )
            ),
        )
    )

    val THINGS = Category(
        "Things", run = 3, listOf(
            PixelArt(
                "Balloon", listOf(
                    ".....KKKKKK.....",
                    "...KKRRRRRRKK...",
                    "..KRRWWRRRRRRK..",
                    ".KRRWRRRRRRRRRK.",
                    ".KRWRRRRRRRRRRK.",
                    ".KRRRRRRRRRRRRK.",
                    ".KRRRRRRRRRRRDK.",
                    ".KRRRRRRRRRRRDK.",
                    "..KRRRRRRRRRDK..",
                    "...KRRRRRRRDK...",
                    "....KKRRRDKK....",
                    "......KDDK......",
                    ".......KK.......",
                    "........K.......",
                    ".......K........",
                    "........K.......",
                    ".........K......",
                )
            ),
            PixelArt(
                "Key", listOf(
                    "....KKKK........",
                    "...KYYYYK.......",
                    "..KYYKKYYK......",
                    "..KYK..KYK......",
                    "..KYYKKYYK......",
                    "...KYYYYK.......",
                    "....KYYK........",
                    "....KYYK........",
                    "....KYYK........",
                    "....KYYKKK......",
                    "....KYYYYK......",
                    "....KYYKKK......",
                    "....KYYK........",
                    "....KYYKK.......",
                    "....KYYYYK......",
                    ".....KKKK.......",
                )
            ),
            PixelArt(
                "Cup", listOf(
                    ".....C...C......",
                    "......C...C.....",
                    ".....C...C......",
                    "..KKKKKKKKKKK...",
                    "..KWWWWWWWWWK...",
                    "..KBBBBBBBBBKKK.",
                    "..KWWWWWWWWWK.K.",
                    "..KWLLWWWLLWK.K.",
                    "..KWWWWWWWWWKKK.",
                    "...KWWWWWWWK....",
                    "....KKKKKKK.....",
                    ".KKKKKKKKKKKKK..",
                    "..KCCCCCCCCCK...",
                    "...KKKKKKKKK....",
                )
            ),
            PixelArt(
                "Umbrella", listOf(
                    ".......K........",
                    ".....KKKKK......",
                    "...KKRRWRRKK....",
                    "..KRRRWWWRRRK...",
                    ".KRRRWWWWWRRRK..",
                    ".KRRRWWWWWRRRK..",
                    "KRRRRWWWWWRRRRK.",
                    "KKKKKKKKKKKKKKK.",
                    ".......B........",
                    ".......B........",
                    ".......B........",
                    ".......B........",
                    ".......B........",
                    ".......B..B.....",
                    "........BB......",
                )
            ),
            PixelArt(
                "Mushroom", listOf(
                    "......KKKK......",
                    "....KKRRWWKK....",
                    "...KRRRRWWWRK...",
                    "..KWWRRRRWWRRK..",
                    ".KWWWWRRRRRRRRK.",
                    ".KWWWWRRRWWRRRK.",
                    "KRWWRRRRWWWWRRRK",
                    "KRRRRRRRWWWWRRRK",
                    "KRRWWRRRRWWRRWWK",
                    "KRWWWWRRRRRRWWWK",
                    ".KKKKKKKKKKKKKK.",
                    "...KSSSSSSSSK...",
                    "...KSSKSSKSSK...",
                    "...KSSSSSSSSK...",
                    "....KSSSSSSK....",
                    ".....KKKKKK.....",
                )
            ),
            PixelArt(
                "House", listOf(
                    "..........CC....",
                    "..........CC....",
                    ".......RR.CC....",
                    "......RRRRCC....",
                    ".....RRRRRRR....",
                    "....RRRRRRRRR...",
                    "...RRRRRRRRRRR..",
                    "..RRRRRRRRRRRRR.",
                    ".RRRRRRRRRRRRRRR",
                    "...TTTTTTTTTTT..",
                    "...TLLTTTTTLLT..",
                    "...TLLTTTTTLLT..",
                    "...TTTTBBBTTTT..",
                    "...TTTTBBBTTTT..",
                    "...TTTTBBBTTTT..",
                    "GGGGGGGGGGGGGGGG",
                )
            ),
        )
    )

    val TRACK = Track(listOf(FRUITS, ANIMALS, FLOWERS, SHAPES, THINGS))
}
